## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('csma', ['network', 'applications'])
    obj.source = [
        'model/backoff.cc',
        'model/csma-net-device.cc',
        'model/csma-channel.cc',
        'helper/csma-helper.cc',
                'model/mycsma-net-device.cc',
                'model/mycsma-channel.cc',
                'model/myswitch-node.cc',
                'model/myrdma-hw.cc',
                'model/myrdma-driver.cc',
                'model/myrdma-queue-pair.cc',
                'helper/mycsma-helper.cc',
        ]
    headers = bld(features='ns3header')
    headers.module = 'csma'
    headers.source = [
        'model/backoff.h',
        'model/csma-net-device.h',
        'model/csma-channel.h',
        'helper/csma-helper.h',
                'model/mycsma-net-device.h',
                'model/mycsma-channel.h',
                'model/myswitch-node.h',
                'model/myrdma-hw.h',
                'model/myrdma-driver.h',
                'model/myrdma-queue-pair.h',
                'helper/mycsma-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
